@startuml
class CreateArticleCategoryTable <<partial>> {
    # <<override>> Up(migrationBuilder:MigrationBuilder) : void
    # <<override>> Down(migrationBuilder:MigrationBuilder) : void
}
Migration <|-- CreateArticleCategoryTable
@enduml
